Repository sprint-team3/GGF, pull requests merged in 2024-04, with the labels that each got.

#259 Hotfix: 랜딩페이지에서 Menu 게임 카테고리 이름 보이지 않는 버그 해결
  src/components/layout/header/Menu/index.tsx
Labels: 🚨ASAP, 버그 해결

#261 Hotfix: 에코 그림자에 마우스 이동 이벤트 적용
  src/components/landing/Echo/index.tsx
  src/hooks/useMouseMoveEffect.ts
Labels: UI 구현

#267 Refactor: UserMenu 로그아웃 클릭 시 페이지 새로고침 로직 추가
  src/components/layout/header/UserMenu/index.tsx
  src/utils/router.ts
Labels: 리팩토링

#268 Refactor: 오버워치 배너 이미지 교체
  public/pngs/banner-OW.png
Labels: 리팩토링

#272 Hotfix: stale Time 변경으로 필요없는 리패칭 로직 삭제
  src/components/postDetail/reservationPanel/ReservationPanel/index.tsx
Labels: 🚨ASAP, 리팩토링

#274 Hotfix: 게시글 목록 상대경로 수정 및 title 데이터 매핑
  src/components/listPage/PostList/index.tsx
Labels: 🚨ASAP, 리팩토링

#280 Feat: 리스트 로딩중일 경우 스켈레톤 카드 UI 적용
  src/components/listPage/ListPageContent/index.tsx
  src/components/listPage/PostList/index.tsx
  src/components/mypage/MyPosts/index.tsx
  src/components/mypage/MyReservations/ReservedTabContent/index.tsx
Labels: UI 구현

#282 Refactor: 등록 수정 페이지 리팩토링
  src/components/createPage/PostForm/index.tsx
  src/components/editPage/EditForm/index.tsx
Labels: 리팩토링

#283 Hotfix: account 페이지 파일 첨부에서 이미지 등록으로 문구 변경
  src/components/AccountForm/index.tsx
Labels: 🚨ASAP, 버그 해결

#284 Hotfix: AuthInputfield 자동완성시 css 수정
  src/components/auth/AuthInputField/AuthInputField.module.scss
Labels: 🚨ASAP, 리팩토링

#288 Hotfix: MatchCard default일 때 이미지 가운데 정렬되도록 수정
  src/components/landing/MatchTeam/MatchCards.module.scss
  src/components/landing/MatchTeam/MatchCards.tsx
Labels: 🚨ASAP, 버그 해결

#290 Hotfix: 랜딩 페이지-클랜 모집/슬라이더 이동 가능할 경우에만 arrow 버튼 나타나게 수정
  src/components/landing/ClanRecruitment/ClanRecruitment.tsx
Labels: 🚨ASAP, 리팩토링

#293 Hotfix: 캘린더 scss에서 미리 정의된 믹스인을 사용하도록 수정
  src/components/calendar/ListBody/ListBody.module.scss
  src/components/calendar/ListCard/ListCard.module.scss
Labels: 리팩토링

#311 Refactor: 마이페이지에서 계정관리 페이지로 이동하는 아이콘 추가
  src/components/commons/ProfileSummary/index.tsx
  src/components/commons/ProfileSummary/profileSummary.module.scss
Labels: 리팩토링

#314 Hotfix: 마이페이지 게임 리스트 queryKey 저장된 상수 파일 사용
  src/components/landing/ClanRecruitment/ClanRecruitment.tsx
Labels: 🚨ASAP, 리팩토링

#317 Hotfix: 디스코드 글자 수 제한 50자로 수정
  src/components/createPage/PostForm/index.tsx
Labels: 🚨ASAP

#318 Hotfix: 등록 페이지 address 오류 수정
  src/components/createPage/PostForm/index.tsx
Labels: 🚨ASAP

#319 Hotfix: 수정 페이지 주소 및 디스코드 글자 수 제한 추가
  src/components/editPage/EditForm/index.tsx
Labels: 🚨ASAP

#320 Hotfix: 이미지 첨부 버튼 타입 submit 으로 수정
  src/components/AccountForm/index.tsx
Labels: 🚨ASAP, 버그 해결

#323 Hotfix: 랜딩페이지-태블릿 이하 디바이스에서 슬라이더가 영역 밖으로 나오는 문제 해결
  src/components/landing/ClanRecruitment/ClanRecruitment.module.scss
Labels: 🚨ASAP, 리팩토링

#328 hotfix: 게시글 목록 queryKey 상수 파일 적용
  src/pages/landing/index.tsx
Labels: 🚨ASAP, 리팩토링

#329 Refactor: 등록 및 수정 페이지의 api 통신 에러 모달 메세지 수정
  src/components/createPage/PostForm/index.tsx
  src/components/editPage/EditForm/index.tsx
  src/constants/inputValidation.ts
Labels: 리팩토링

#330 Hotfix: 예약현황 모달창 바깥 클릭시 닫히는 기능 추가
  src/components/calendar/index.tsx
  src/components/commons/modals/CustomCommonModal.tsx
Labels: 기능 구현

#335 Hotfix: getFormatDate 유틸 함수를 utc로 수정
  src/utils/getDate.ts
Labels: 🚨ASAP

#348 Refactor: 등록 및 수정 페이지 스키마 분리
  src/apis/activities/schema.ts
  src/components/createPage/PostForm/index.tsx
  src/components/editPage/EditForm/index.tsx
  src/constants/postForm.ts
Labels: 리팩토링

#349 Refactor: 온라인, 오프라인 모집 카드만 평점을 보여주도록 수정
  src/components/commons/cards/CommonCard.tsx
Labels: 리팩토링
