Repository sprint-team3/GGF, pull requests merged in 2024-03, with the labels that each got.

#6 feat: apiPath 구현 및 eslint 룰 수정
  .eslintrc.json
  src/constants/apiPaths.ts
  src/constants/index.ts
Labels: 기능 구현

#10 hotfix: 타입 이름 변경
  src/apis/activities.ts
  src/types/activities.ts
Labels: 🚨ASAP

#8 Feat[#2]: api 추상화, eslint import문 룰 수정, PR 템플릿 수정
  .eslintrc.json
  .github/pull_request_template.md
  src/apis/myNotifications.ts
  src/apis/myReservations.ts
  src/apis/users.ts
  src/types/index.ts
  src/types/myNotifications.ts
  src/types/myReservations.ts
  src/types/users.ts
Labels: 기능 구현, 문서

#29 hotfix: Activities 타입명 변경 및 api 객체 프로퍼티 순서 변경
  src/apis/activities.ts
  src/types/activities.ts
Labels: 🚨ASAP

#40 hotfix: 버튼 스타일 오류 수정
  src/components/commons/buttons/BaseButton.module.scss
Labels: 🚨ASAP, 버그 해결

#36 Feat[#15]: 공용 Profile 관련 컴포넌트 구현
  public/svgs/alarmEmpty.svg
  public/svgs/alarmFull.svg
  public/svgs/arrowBottom.svg
  public/svgs/arrowTop.svg
  public/svgs/profileDefault.svg
  src/components/HeaderProfile/HeaderProfile.module.scss
  src/components/HeaderProfile/index.tsx
  src/components/commons/Alarm/Alarm.module.scss
  src/components/commons/Alarm/index.tsx
  src/components/commons/Avatar/Avatar.module.scss
  src/components/commons/Avatar/index.tsx
  src/constants/breakPoint.ts
  src/constants/images.ts
  src/constants/index.ts
  src/constants/times.ts
  src/hooks/temps
  src/hooks/useDeviceType.ts
  src/types/devicetype.ts
  src/types/index.ts
Labels: 기능 구현, 공통 UI

#43 Feat: 공용 컴포넌트 story 추가
  .storybook/main.ts
  src/stories/Alarm.stories.ts
  src/stories/Avatar.stories.ts
  src/stories/ReviewCard.stories.ts
  src/stories/StarRating.stories.ts
  src/types/index.ts
Labels: 중요도 낮음

#51 Chore: react hook form 중복 코드 삭제
  package.json
Labels: 🚨ASAP, 환경

#52 Refactor: isErrorVisible이 true일 때만 에러메시지가 보이도록 수정
  src/components/commons/InputField/index.tsx
Labels: 🚨ASAP, 리팩토링

#57 Hotfix: 컨벤션에 맞게 프로퍼티명 수정
  src/components/commons/buttons/BaseButton.tsx
  src/components/commons/buttons/OperationButton.tsx
Labels: 리팩토링

#60 HotFix: package-lock.json 추가, gitignore 수정
  .gitignore
  package-lock.json
Labels: 🚨ASAP, 문서

#59 Hotfix: InputField의 background를 $input-background로 변경
  src/components/commons/InputField/InputField.module.scss
  src/styles/variables/_colors.scss
Labels: 🚨ASAP, 리팩토링

#65 Hotfix[#11]: 공용 버튼 컴포넌트들 buttons 폴더의 index.ts에 export 추가
  src/components/commons/buttons/index.ts
  src/stories/ArrowButton.stories.ts
  src/stories/BaseButton.stories.ts
  src/stories/CountButton.stories.ts
  src/stories/MoreButton.stories.ts
  src/stories/OperationButton.stories.ts
Labels: 🚨ASAP

#89 Refactor: 스토리북 컴포넌트 그룹 추가
  src/stories/Alarm.stories.ts
  src/stories/Avatar.stories.ts
  src/stories/Badge.stories.ts
  src/stories/ReviewCard.stories.ts
  src/stories/Tab.stories.ts
  src/stories/Tag.stories.ts
Labels: 중요도 낮음, 리팩토링

#93 HotFIx: Kebabmenu 리팩토링
  src/components/commons/Kebabmenu/Kebabmenu.module.scss
  src/components/commons/Kebabmenu/index.tsx
Labels: 🚨ASAP, 리팩토링

#105 Hotfix: getExpirationDate 함수 이름 변경
  src/components/commons/cards/ReservedCard.tsx
  src/utils/getDate.ts
Labels: 🚨ASAP, 리팩토링

#107 Hotfix: StarRating 컴포넌트 readonly 고정값 false로 변경
  src/components/commons/StarRating/index.tsx
Labels: 🚨ASAP, 리팩토링

#114 Refactor[#113]: Filter 컴포넌트의 부정 조건문을 early return 문으로 변경
  src/components/commons/Filter/index.tsx
Labels: 리팩토링

#122 Refactor[#53]: useSignin 리팩토링
  src/hooks/useSignin.ts
Labels: 리팩토링

#121 refactor[#102]: Dropdown 리팩토링
  src/components/commons/inputs/Dropdown.tsx
Labels: 리팩토링

#129 Hotfix: onError 삭제
  src/hooks/useSignin.ts
Labels: 🚨ASAP, 리팩토링

#130 Hotfix: confirmModal renderButton 변경에 따른 수정
  src/components/commons/inputs/ImageField.tsx
Labels: 🚨ASAP, 리팩토링

#131 Hotfix: Confirm모달 사용처에서 Button 넣는법 수정
  src/components/commons/cards/RegisteredCard.tsx
  src/components/commons/cards/ReservedCard.tsx
Labels: 🚨ASAP, 버그

#136 Hotfix : Header 컴포넌트 fixed 속성 적용
  src/components/layout/header/Header/Header.module.scss
  src/components/layout/header/Header/index.tsx
Labels: 리팩토링

#139 Hotfix: useMultipleTogglePopup 커스텀 훅 삭제
  src/components/layout/header/Header/index.tsx
  src/hooks/useMultipleTogglePopup.ts
Labels: 리팩토링

#144 Hotfix: README.md 현기님 닉네임 수정
  README.md
Labels: 🚨ASAP, 문서

#145 Hotfix: DrawerMenu 위치 수정
  src/components/layout/header/Header/Header.module.scss
Labels: 🚨ASAP, 리팩토링

#148 Hotfix: Tab 컴포넌트 export default 수정
  src/components/commons/Tab/index.tsx
  src/stories/Tab.stories.ts
Labels: 🚨ASAP

#156 Hotfix: label없을 때 focus되면 border-color primary로 변경
  src/components/commons/inputs/TextField.module.scss
  src/components/commons/inputs/TextField.tsx
Labels: 🚨ASAP, 리팩토링

#157 Hotfix: BaseButton에 type 추가
  src/components/commons/buttons/BaseButton.tsx
Labels: 🚨ASAP

#158 Hotfix: 필터 리스트 모바일에서 잘리는 오류 해결
  src/components/commons/Filter/Filter.module.scss
  src/stories/Filter.stories.ts
Labels: 🚨ASAP, 버그

#160 Hotfix: body 고정 스크롤바 영역 지정, html 스크롤바 유지되는 속성 추가
  src/styles/base/_reset.scss
Labels: 🚨ASAP, 버그 해결, 리팩토링

#162 Hotfix: tabContentMap 객체 분리
  src/components/mypage/MypageContent/index.tsx
Labels: 🚨ASAP, 리팩토링

#166 Hotfix: onChange prop 추가
  src/components/commons/StarRating/index.tsx
Labels: 🚨ASAP, 리팩토링

#168 Hotfix: TextField라벨없을시 라벨 영역 삭제, thick scrollbar 디자인 수정
  src/components/commons/inputs/TextField.module.scss
  src/components/commons/inputs/TextField.tsx
  src/styles/mixins/_scrollbar.scss
Labels: 🚨ASAP, 버그 해결

#170 Hotfix: options의 value가 string도 받을 수 있게 타입 수정
  src/components/commons/inputs/FormDropdown.tsx
Labels: 🚨ASAP, 리팩토링

#175 Hotfix: 정렬 관련 타입 추가
  src/types/sort.ts
Labels: 🚨ASAP

#176 Hotfix: EmptyCard에 border radius 추가
  src/components/layout/empty/EmptyCard/EmptyCard.module.scss
Labels: 🚨ASAP

#180 Hotfix: TextField 실시간 글자수 반영 안 되는 버그 해결
  src/components/commons/inputs/TextField.tsx
Labels: 🚨ASAP, 버그 해결

#187 Hotfix: 베이스버튼 disabled일때 호버되는 오류 해결
  src/components/commons/buttons/BaseButton.module.scss
Labels: 버그 해결

#191 Hotfix: 스케줄 타입 따로 분리
  src/types/activities.ts
  src/types/index.ts
  src/types/schedule.ts
Labels: 🚨ASAP, 리팩토링

#192 Hotfix: 페이지네이션 ul 에 li 태그 추가
  src/components/commons/Pagination/index.tsx
Labels: 🚨ASAP

#194 Hotfix: useDeviceType의 useState 초기값 수정
  src/hooks/useDeviceType.ts
Labels: 🚨ASAP, 버그 해결

#198 Hotfix: description에 discord 항목 추가
  src/components/postCreate/PostForm/index.tsx
Labels: 🚨ASAP

#199 Hotfix: ImageField 옵셔널 프롭 및 리스트 css 수정
  src/components/commons/inputs/ImageField.module.scss
  src/components/commons/inputs/ImageField.tsx
Labels: 🚨ASAP, 버그 해결, 리팩토링

#210 Hotfix: 모달 버튼 컴포넌트 variant 속성 추가, 누락된 dependency 추가
  src/components/postDetail/reservationPanel/ReservationPanel/index.tsx
Labels: 🚨ASAP, 리팩토링

#213 Refactor: profileSummary 정렬 속성 추가
  src/components/commons/ProfileSummary/profileSummary.module.scss
Labels: 리팩토링

#215 Hotfix: PostFormDropdown 컴포넌트 추가 및 적용
  src/components/commons/inputs/PostFormDropdown.module.scss
  src/components/commons/inputs/PostFormDropdown.tsx
  src/components/commons/inputs/index.ts
  src/components/createPage/PostForm/index.tsx
  src/components/createPage/Schedule/index.tsx
Labels: 🚨ASAP

#217 Hotfix: 기본 프로필 이미지 클래스네임 삭제
  src/components/commons/Avatar/index.tsx
Labels: 🚨ASAP

#220 Refactor[#219] : 모집 등록 기능 추가
  src/components/createPage/PostForm/index.tsx
  src/constants/postForm.ts
  src/utils/gameFormatter.ts
Labels: 리팩토링

#237 Hotfix: userStore에서 유저 데이터 참조, early return 문 삭제, 조건부 렌더링 적용
  src/components/postDetail/PostDetailContent/index.tsx
Labels: 🚨ASAP, 리팩토링

#243 Hotfix: 로그인 회원가입 폼 로고 클릭시 랜딩으로 이동, AuthInputField background 수정
  src/components/auth/SigninForm/index.tsx
  src/components/auth/SignupForm/index.tsx
Labels: 🚨ASAP, 버그 해결

#255 Refactor[#254]: PostForm 이미지 등록 기능 수정
  src/apis/activities.ts
  src/components/createPage/PostForm/index.tsx
Labels: 🚨ASAP, 리팩토링
